/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassParticipantSchema extends BaseModel {
  static $columns = ['classId', 'joinedAt', 'userId'] as const
  $columns = ClassParticipantSchema.$columns
  @column({ isPrimary: true })
  declare classId: string
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare userId: string
}

export class ClassSchema extends BaseModel {
  static $columns = [
    'club',
    'createdAt',
    'duration',
    'id',
    'isPublished',
    'levelMax',
    'levelMin',
    'location',
    'maxPlayers',
    'name',
    'scheduledAt',
    'teacherId',
  ] as const
  $columns = ClassSchema.$columns
  @column()
  declare club: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPublished: boolean
  @column({ consume: (v: string | null) => (v !== null ? Number.parseFloat(v) : null) })
  declare levelMax: number | null
  @column({ consume: (v: string | null) => (v !== null ? Number.parseFloat(v) : null) })
  declare levelMin: number | null
  @column()
  declare location: string | null
  @column()
  declare maxPlayers: number
  @column()
  declare name: string
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare teacherId: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'club',
    'createdAt',
    'email',
    'firstName',
    'id',
    'lastName',
    'level',
    'location',
    'password',
    'profilePicture',
    'role',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare club: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string
  @column()
  declare level: number | null
  @column()
  declare location: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare profilePicture: string | null
  @column()
  declare role: string
}
